### ISSUE TITLE
MathJax system wide directory is not available in production environment

### ISSUE THREAD

**Issue by suryateja619** [pmq20/mathjax-rails#23]
I used the configuration specified in the readme file but unfortunately, when I run it in production the systemwide directory mathjax is not loaded. 

I'm getting error: Uncaught ReferenceError: MathJax is not defined

How to get the mathjax folder to be available in production?

**Comment by suryateja619** [comment]
This is the error message we're seeing in the production environment in the log file. 

``` RuntimeError (In order to use #url_for, you must include routing helpers explicitly. For instance, `include Rails.application.routes.url_helpers`.): ```

**Comment by manusajith** [comment]
@suryateja619 Whats the rails version you are using?

**Comment by suryateja619** [comment]
@manusajith Rails 4.2.7
